In [1]:
CONNECTION_PARAMETERS = {
    'url': "snowhouse.snowflakecomputing.com",
    'host': "snowhouse.snowflakecomputing.com",
    'account': 'snowhouse',
    'user': 'pdorairaj',
    'authenticator': 'externalbrowser',
    'schema': 'au',
    'database': 'snowhouse_import',
    'warehouse': 'snowhouse',
}

PRM_QA1 = {
    'account': 'snowflake',
    'user': 'admin',
    'password': 'test',
    'protocol': 'http',
    'host': 'snowflake.qa1.int.snowflakecomputing.com',
    'port': '8084',
    'schema': 'public',
    'database': 'bjiang',
    'warehouse': 'compute_service_wh',   
}

PRM = {
    'account': 'snowflake',
    'user': 'admin',
    'password': 'test',
    'protocol': 'http',
    'host': 'snowflake.dev.local',
    'port': '8082',
    'schema': 'transformers',
    'database': 'feature_engineering',
    'warehouse': 'compute_service_warehouse',   
}
from snowflake.snowpark import Session

session = Session.builder.configs(PRM_QA1).create()
print(session.sql('select current_warehouse(), current_database(), current_schema()').collect())


[Row(CURRENT_WAREHOUSE()='COMPUTE_SERVICE_WH', CURRENT_DATABASE()='BJIANG', CURRENT_SCHEMA()='PUBLIC')]


In [2]:
print(session.sql('select current_warehouse(), current_database(), current_schema()').collect())

dataframe = session.sql('select * from iris_data')
dataset = session.dataset(dataframe)
min_max_scaler1 = session.MinMaxEstimator(input_columns=['COL1', 'COL2'],
                                          output_columns=['COL1_scaled', 'COL2_scaled']
                                         );
imputer = session.Imputer(input_columns=['COL3', 'COL4'],
                          output_columns=['COL3_imputed', 'COL4_imputed']
                         );
min_max_scaler2 = session.MinMaxEstimator(input_columns=['COL3_imputed', 'COL4_imputed'],
                                          output_columns=['COL3_scaled', 'COL4_scaled']
                                         );
pipeline = session.Pipeline([imputer, min_max_scaler2])
pipeline = pipeline.fit(dataset)
dataset = pipeline.transform(dataset)

#pt_dataset = snowml.torch.dataset(dataset)

#model = nn.Model

#for batch in dataloader(pt_dataset):
    
dataset.to_pandas()


# Or:

#res = session.table('DEPLOYMENT_METADATA').collect()

[Row(CURRENT_WAREHOUSE()='COMPUTE_SERVICE_WAREHOUSE', CURRENT_DATABASE()='FEATURE_ENGINEERING', CURRENT_SCHEMA()='TRANSFORMERS')]
insert into columns_metadata select '08fc8df7-d0cb-4176-a0d3-9e642416be36', 'COL1', 'double', 'place_holder', false, NULL, object_construct('min', 1.0,'max', 7.9,'avg', 5.748366013071895);
insert into columns_metadata select '08fc8df7-d0cb-4176-a0d3-9e642416be36', 'COL2', 'double', 'place_holder', false, NULL, object_construct('min', 2.0,'max', 4.4,'avg', 3.036601307189543);
insert into columns_metadata select '08fc8df7-d0cb-4176-a0d3-9e642416be36', 'COL3', 'double', 'place_holder', false, NULL, object_construct('min', 1.0,'max', 6.9,'avg', 3.7580000000000005);
insert into columns_metadata select '08fc8df7-d0cb-4176-a0d3-9e642416be36', 'COL4', 'double', 'place_holder', false, NULL, object_construct('min', 0.1,'max', 5.567,'avg', 1.2282582781456954);
insert into columns_metadata select '08fc8df7-d0cb-4176-a0d3-9e642416be36', 'PREDICT', 'double', 'place_holder

COL1  COL2  COL3   COL4  PREDICT  COL3_IMPUTED  COL4_IMPUTED  \
0     5.1   3.5   1.4  0.200        0         1.400      0.200000   
1     4.9   3.0   1.4  0.200        0         1.400      0.200000   
2     4.7   3.2   1.3  0.200        0         1.300      0.200000   
3     4.6   3.1   1.5  0.200        0         1.500      0.200000   
4     5.0   3.6   1.4  0.200        0         1.400      0.200000   
..    ...   ...   ...    ...      ...           ...           ...   
148   6.2   3.4   5.4  2.300        2         5.400      2.300000   
149   5.9   3.0   5.1  1.800        2         5.100      1.800000   
150   1.0   2.0   NaN    NaN        0         3.758      1.228258   
151   1.0   2.0   NaN  5.567        0         3.758      5.567000   
152   1.0   2.0   NaN    NaN        0         3.758      1.228258   

     COL3_SCALED  COL4_SCALED  
0       0.067797     0.018292  
1       0.067797     0.018292  
2       0.050847     0.018292  
3       0.084746     0.018292  
4       0.067797     0.018292  
..           ...          ...  
148     0.745763     0.402414  
149     0.694915     0.310957  
150     0.467458     0.206376  
151     0.467458     1.000000  
152     0.467458     0.206376  

[153 rows x 9 columns]

In [3]:
dataset = session.sql('select * from iris_data')
dataset = session.dataset(dataset)
# use stored procedure
dataset

min_max_scaler = session.MinMaxEstimator(input_columns=['COL1', 'COL2'], output_columns=['COL1_scaled', 'COL2_scaled']);
min_max_model = min_max_scaler.fit(dataset)
min_max_model
# use Stored Procedure 
# fit_run_id = storedprocedure(dataframe, input_cols, output_cols)
dataset = min_max_model.transform(dataset)
dataset
# transform will be a SP

# dataframe = storedprocedure(dataframe, fit_run_id) -- instead of returning a dataframe, we can return a column expression

select * from columns_metadata where dataset_version = 'cexzaqnjug' and column_name = 'COL1';
select * from columns_metadata where dataset_version = 'cexzaqnjug' and column_name = 'COL2';


In [2]:
imputer = session.Imputer(input_columns=['COL3', 'COL4'],
                          output_columns=['COL3_imputed', 'COL4_imputed']
                         );

In [3]:
dataset = session.sql('select * from iris_data')
dataset = session.dataset(dataset)
m = imputer.fit(dataset)

insert into columns_metadata select '9e4dd98e-e20c-4d58-b327-b88cf5677839', 'COL1', 'double', 'place_holder', false, NULL, object_construct('min', 1.0,'max', 7.9,'avg', 5.779605263157895);
insert into columns_metadata select '9e4dd98e-e20c-4d58-b327-b88cf5677839', 'COL2', 'double', 'place_holder', false, NULL, object_construct('min', 2.0,'max', 4.4,'avg', 3.043421052631579);
insert into columns_metadata select '9e4dd98e-e20c-4d58-b327-b88cf5677839', 'COL3', 'double', 'place_holder', false, NULL, object_construct('min', 1.0,'max', 6.9,'avg', 3.7580000000000005);
insert into columns_metadata select '9e4dd98e-e20c-4d58-b327-b88cf5677839', 'COL4', 'double', 'place_holder', false, NULL, object_construct('min', 0.1,'max', 5.567,'avg', 1.2282582781456954);
insert into columns_metadata select '9e4dd98e-e20c-4d58-b327-b88cf5677839', 'PREDICT', 'double', 'place_holder', false, NULL, object_construct('min', 0,'max', 2,'avg', 0.986842);
select * from columns_metadata where dataset_version = '9e4dd

In [4]:
m

In [5]:
d = m.transform(dataset)
d.to_pandas()

select * from columns_metadata where dataset_version = '9e4dd98e-e20c-4d58-b327-b88cf5677839' and column_name = 'COL3';
select * from columns_metadata where dataset_version = '9e4dd98e-e20c-4d58-b327-b88cf5677839' and column_name = 'COL4';
with temp_table as ( select * from iris_data ) select *, coalesce(COL3, 3.7580000000000005) as COL3_imputed, coalesce(COL4, 1.2282582781456954) as COL4_imputed from temp_table


COL1  COL2  COL3   COL4  PREDICT  COL3_IMPUTED  COL4_IMPUTED
0     5.1   3.5   1.4  0.200        0         1.400      0.200000
1     4.9   3.0   1.4  0.200        0         1.400      0.200000
2     4.7   3.2   1.3  0.200        0         1.300      0.200000
3     4.6   3.1   1.5  0.200        0         1.500      0.200000
4     5.0   3.6   1.4  0.200        0         1.400      0.200000
..    ...   ...   ...    ...      ...           ...           ...
147   6.5   3.0   5.2  2.000        2         5.200      2.000000
148   6.2   3.4   5.4  2.300        2         5.400      2.300000
149   5.9   3.0   5.1  1.800        2         5.100      1.800000
150   1.0   2.0   NaN    NaN        0         3.758      1.228258
151   1.0   2.0   NaN  5.567        0         3.758      5.567000

[152 rows x 7 columns]

In [4]:
min_max_scaler2 = session.MinMaxEstimator(input_columns=['COL3', 'COL4'], output_columns=['COL3_scaled', 'COL4_scaled']);
min_max_model2 = min_max_scaler2.fit(dataset)
min_max_model2
# use Stored Procedure 
# fit_run_id = storedprocedure(dataframe, input_cols, output_cols)
dataset = min_max_model2.transform(dataset)
dataset
# transform will be a SP

# dataframe = storedprocedure(dataframe, fit_run_id) -- instead of returning a dataframe, we can return a column expression
dataset.to_pandas()

select * from columns_metadata where dataset_version = 'cexzaqnjug' and column_name = 'COL3';
select * from columns_metadata where dataset_version = 'cexzaqnjug' and column_name = 'COL4';


COL1  COL2  COL3  COL4  PREDICT  COL1_SCALED  COL2_SCALED  COL3_SCALED  \
0     5.1   3.5   1.4   0.2        0     0.222222     0.625000     0.067797   
1     4.9   3.0   1.4   0.2        0     0.166667     0.416667     0.067797   
2     4.7   3.2   1.3   0.2        0     0.111111     0.500000     0.050847   
3     4.6   3.1   1.5   0.2        0     0.083333     0.458333     0.084746   
4     5.0   3.6   1.4   0.2        0     0.194444     0.666667     0.067797   
..    ...   ...   ...   ...      ...          ...          ...          ...   
145   6.7   3.0   5.2   2.3        2     0.666667     0.416667     0.711864   
146   6.3   2.5   5.0   1.9        2     0.555556     0.208333     0.677966   
147   6.5   3.0   5.2   2.0        2     0.611111     0.416667     0.711864   
148   6.2   3.4   5.4   2.3        2     0.527778     0.583333     0.745763   
149   5.9   3.0   5.1   1.8        2     0.444444     0.416667     0.694915   

     COL4_SCALED  
0       0.041667  
1       0.041667  
2       0.041667  
3       0.041667  
4       0.041667  
..           ...  
145     0.916667  
146     0.750000  
147     0.791667  
148     0.916667  
149     0.708333  

[150 rows x 9 columns]

select * from columns_metadata where dataset_version = 'yxmfzoerdi' and column_name = 'COL1';
select * from columns_metadata where dataset_version = 'yxmfzoerdi' and column_name = 'COL2';
with temp_table as ( select * from iris_data ) select *, (COL1 - 4.3)/(7.9 - 4.3) as COL1_scaled, (COL2 - 2)/(4.4 - 2) as COL2_scaled from temp_table;


In [4]:
print(session.sql('select current_warehouse(), current_database(), current_schema()').collect())


dataframe = session.sql('select FARE_AMOUNT from nytrain')
dataset = session.dataset(dataframe)
imputer = session.Imputer(input_columns=['FARE_AMOUNT'],
                          output_columns=['FARE_AMOUNT_IMPUTED']
                         );
min_max_scaler2 = session.MinMaxEstimator(input_columns=['FARE_AMOUNT_IMPUTED'],
                                          output_columns=['FARE_AMOUNT_SCALED']
                                         );
pipeline = session.Pipeline([imputer, min_max_scaler2])
pipeline = pipeline.fit(dataset)
dataset = pipeline.transform(dataset)

#pt_dataset = snowml.torch.dataset(dataset)

#model = nn.Model

#for batch in dataloader(pt_dataset):
    
#dataset.to_pandas()

[Row(CURRENT_WAREHOUSE()='COMPUTE_SERVICE_WH', CURRENT_DATABASE()='BJIANG', CURRENT_SCHEMA()='PUBLIC')]
insert into columns_metadata select '81e23787-658c-44bd-8209-8517fefa16f2', 'FARE_AMOUNT', 'double', 'place_holder', false, NULL, object_construct('min', -300.0,'max', 93963.36,'avg', 11.345045601662935);
select * from columns_metadata where dataset_version = '81e23787-658c-44bd-8209-8517fefa16f2' and column_name = 'FARE_AMOUNT';
insert into columns_metadata select '81e23787-658c-44bd-8209-8517fefa16f2', 'FARE_AMOUNT_IMPUTED', 'double', 'place_holder', false, NULL, object_construct('min', -300,'max', 93963.36,'avg', 11.345045601662935);
select * from columns_metadata where dataset_version = '81e23787-658c-44bd-8209-8517fefa16f2' and column_name = 'FARE_AMOUNT';
with temp_table_cde1b28f_6608_4e63_bce1_cc729d2626a1 as ( select FARE_AMOUNT from nytrain ) select *, coalesce(FARE_AMOUNT, 11.345045601662935) as FARE_AMOUNT_IMPUTED from temp_table_cde1b28f_6608_4e63_bce1_cc729d2626a1
select

In [5]:
dataset

In [7]:
pdf = dataset.to_pandas()

In [8]:
pdf.memory_usage()

Index                        128
FARE_AMOUNT            443390848
FARE_AMOUNT_IMPUTED    443390848
FARE_AMOUNT_SCALED     443390848
dtype: int64

In [4]:
import time
s = time.time_ns()
dataframe = session.sql('select FARE_AMOUNT from nytrain')
dataset = session.dataset(dataframe)
imputer = session.Imputer(input_columns=['FARE_AMOUNT'],
                          output_columns=['FARE_AMOUNT_IMPUTED']
                         );
min_max_scaler2 = session.MinMaxEstimator(input_columns=['FARE_AMOUNT_IMPUTED'],
                                          output_columns=['FARE_AMOUNT_SCALED']
                                         );
pipeline = session.Pipeline([imputer, min_max_scaler2])
pipeline = pipeline.fit(dataset)
e = time.time_ns()
print (str((e-s)/1000000) + " ms")

10666.476276 ms


In [5]:
s = time.time_ns()
transformed_dataset = pipeline.transform(dataset)
e = time.time_ns()
print (str((e-s)/1000000) + " ms")

1435.49792 ms


In [7]:
from sklearn.linear_model import SGDClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=1)
clf.fit(X, y)


/home/pdorairaj/.local/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDClassifier(max_iter=1)

In [12]:
clf.coef_

array([[9.99000999, 9.99000999]])

In [10]:
clf.intercept_

array([0.00999001])

In [11]:
clf.fit(X, y)

/home/pdorairaj/.local/lib/python3.8/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDClassifier(max_iter=1)

In [13]:
clf.intercept_

array([0.00999001])